name: time_finder
description: A Dart package for DateTime manipulation boundary calculations, offsets, and time unit handling.
version: 1.0.1
repository: https://github.com/Hisham-Malik/time_finder
homepage: https://github.com/Hisham-Malik/time_finder
issue_tracker: https://github.com/Hisham-Malik/time_finder/issues
documentation: https://pub.dev/documentation/time_finder/latest/
metadata:
  license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  dartdoc: ^8.1.0
  lints: ^4.0.0
  test: ^1.24.0