name: time_finder
description: A Dart package providing powerful utilities for manipulating and querying DateTime objects. Easily calculate time unit boundaries, apply date offsets, and work with custom time units such as seconds, minutes, hours, days, weeks, months, and years.
version: 1.0.0
repository: https://github.com/Hisham-Malik/time_finder
homepage: https://github.com/Hisham-Malik/time_finder
issue_tracker: https://github.com/Hisham-Malik/time_finder/issues
documentation: https://pub.dev/documentation/time_finder/latest/
metadata:
  license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0